import Foundation

// ═══════════════════════════════════════════════════════════
//  Erweiterungswortschatz (v1.7) — Konversationsniveau.
//  Nomen-Artikel & Plurale werden per QA-Skript gegen
//  de.wiktionary validiert (siehe CLAUDE.md).
// ═══════════════════════════════════════════════════════════
extension GermanData {

    static let words: [GWord] = dedupe(coreWords + moreWords)
    static let phrases: [GPhrase] = corePhrases + morePhrases

    private static func dedupe(_ list: [GWord]) -> [GWord] {
        var seen = Set<String>()
        return list.filter { seen.insert($0.de.lowercased()).inserted }
    }

    static let moreWords: [GWord] = [
        // ── Ăn uống ──
        GWord(de: "Frühstück", art: "das", pl: nil, vi: "bữa sáng", cat: "Ăn uống", note: ""),
        GWord(de: "Mittagessen", art: "das", pl: nil, vi: "bữa trưa", cat: "Ăn uống", note: ""),
        GWord(de: "Abendessen", art: "das", pl: nil, vi: "bữa tối", cat: "Ăn uống", note: ""),
        GWord(de: "Restaurant", art: "das", pl: "Restaurants", vi: "nhà hàng", cat: "Ăn uống", note: ""),
        GWord(de: "Speisekarte", art: "die", pl: "Speisekarten", vi: "thực đơn", cat: "Ăn uống", note: ""),
        GWord(de: "Kellner", art: "der", pl: "Kellner", vi: "người phục vụ", cat: "Ăn uống", note: ""),
        GWord(de: "Trinkgeld", art: "das", pl: "Trinkgelder", vi: "tiền boa", cat: "Ăn uống", note: ""),
        GWord(de: "Gabel", art: "die", pl: "Gabeln", vi: "cái nĩa", cat: "Ăn uống", note: ""),
        GWord(de: "Messer", art: "das", pl: "Messer", vi: "con dao", cat: "Ăn uống", note: ""),
        GWord(de: "Löffel", art: "der", pl: "Löffel", vi: "cái thìa", cat: "Ăn uống", note: "miền Nam: cái muỗng"),
        GWord(de: "Teller", art: "der", pl: "Teller", vi: "cái đĩa", cat: "Ăn uống", note: ""),
        GWord(de: "Tasse", art: "die", pl: "Tassen", vi: "tách, cốc", cat: "Ăn uống", note: ""),
        GWord(de: "Glas", art: "das", pl: "Gläser", vi: "cái ly", cat: "Ăn uống", note: ""),
        GWord(de: "Flasche", art: "die", pl: "Flaschen", vi: "cái chai", cat: "Ăn uống", note: ""),
        GWord(de: "Suppe", art: "die", pl: "Suppen", vi: "món canh, súp", cat: "Ăn uống", note: ""),
        GWord(de: "Nudel", art: "die", pl: "Nudeln", vi: "mì, sợi mì", cat: "Ăn uống", note: ""),
        GWord(de: "Kartoffel", art: "die", pl: "Kartoffeln", vi: "khoai tây", cat: "Ăn uống", note: ""),
        GWord(de: "Tomate", art: "die", pl: "Tomaten", vi: "cà chua", cat: "Ăn uống", note: ""),
        GWord(de: "Zwiebel", art: "die", pl: "Zwiebeln", vi: "hành tây", cat: "Ăn uống", note: ""),
        GWord(de: "Knoblauch", art: "der", pl: nil, vi: "tỏi", cat: "Ăn uống", note: ""),
        GWord(de: "Apfel", art: "der", pl: "Äpfel", vi: "quả táo", cat: "Ăn uống", note: ""),
        GWord(de: "Banane", art: "die", pl: "Bananen", vi: "quả chuối", cat: "Ăn uống", note: ""),
        GWord(de: "Orange", art: "die", pl: "Orangen", vi: "quả cam", cat: "Ăn uống", note: ""),
        GWord(de: "Zitrone", art: "die", pl: "Zitronen", vi: "quả chanh", cat: "Ăn uống", note: ""),
        GWord(de: "Traube", art: "die", pl: "Trauben", vi: "quả nho", cat: "Ăn uống", note: ""),
        GWord(de: "Erdbeere", art: "die", pl: "Erdbeeren", vi: "quả dâu tây", cat: "Ăn uống", note: ""),
        GWord(de: "Mango", art: "die", pl: "Mangos", vi: "quả xoài", cat: "Ăn uống", note: ""),
        GWord(de: "Kuchen", art: "der", pl: "Kuchen", vi: "bánh ngọt", cat: "Ăn uống", note: ""),
        GWord(de: "Schokolade", art: "die", pl: "Schokoladen", vi: "sô-cô-la", cat: "Ăn uống", note: ""),
        GWord(de: "Eis", art: "das", pl: nil, vi: "kem; nước đá", cat: "Ăn uống", note: ""),
        GWord(de: "Butter", art: "die", pl: nil, vi: "bơ", cat: "Ăn uống", note: ""),
        GWord(de: "Käse", art: "der", pl: nil, vi: "phô mai", cat: "Ăn uống", note: ""),
        GWord(de: "Wurst", art: "die", pl: "Würste", vi: "xúc xích", cat: "Ăn uống", note: ""),
        GWord(de: "Schinken", art: "der", pl: "Schinken", vi: "giăm bông", cat: "Ăn uống", note: ""),
        GWord(de: "Hähnchen", art: "das", pl: "Hähnchen", vi: "gà (món ăn)", cat: "Ăn uống", note: ""),
        GWord(de: "Rindfleisch", art: "das", pl: nil, vi: "thịt bò", cat: "Ăn uống", note: ""),
        GWord(de: "Schweinefleisch", art: "das", pl: nil, vi: "thịt heo", cat: "Ăn uống", note: ""),
        GWord(de: "Garnele", art: "die", pl: "Garnelen", vi: "con tôm", cat: "Ăn uống", note: ""),
        GWord(de: "Öl", art: "das", pl: "Öle", vi: "dầu ăn", cat: "Ăn uống", note: ""),
        GWord(de: "Pfeffer", art: "der", pl: nil, vi: "hạt tiêu", cat: "Ăn uống", note: ""),
        GWord(de: "Soße", art: "die", pl: "Soßen", vi: "nước sốt", cat: "Ăn uống", note: ""),
        GWord(de: "Bier", art: "das", pl: "Biere", vi: "bia", cat: "Ăn uống", note: ""),
        GWord(de: "Wein", art: "der", pl: "Weine", vi: "rượu vang", cat: "Ăn uống", note: ""),
        GWord(de: "Saft", art: "der", pl: "Säfte", vi: "nước ép", cat: "Ăn uống", note: ""),
        GWord(de: "Brötchen", art: "das", pl: "Brötchen", vi: "bánh mì nhỏ", cat: "Ăn uống", note: ""),
        GWord(de: "Marmelade", art: "die", pl: "Marmeladen", vi: "mứt", cat: "Ăn uống", note: ""),
        GWord(de: "Honig", art: "der", pl: nil, vi: "mật ong", cat: "Ăn uống", note: ""),
        GWord(de: "Joghurt", art: "der", pl: "Joghurts", vi: "sữa chua", cat: "Ăn uống", note: ""),
        GWord(de: "Pfanne", art: "die", pl: "Pfannen", vi: "cái chảo", cat: "Ăn uống", note: ""),
        GWord(de: "Topf", art: "der", pl: "Töpfe", vi: "cái nồi", cat: "Ăn uống", note: ""),
        GWord(de: "Herd", art: "der", pl: "Herde", vi: "bếp nấu", cat: "Ăn uống", note: ""),
        GWord(de: "Kühlschrank", art: "der", pl: "Kühlschränke", vi: "tủ lạnh", cat: "Ăn uống", note: ""),
        GWord(de: "Backofen", art: "der", pl: "Backöfen", vi: "lò nướng", cat: "Ăn uống", note: ""),

        // ── Cơ thể ──
        GWord(de: "Kopf", art: "der", pl: "Köpfe", vi: "cái đầu", cat: "Cơ thể", note: ""),
        GWord(de: "Haar", art: "das", pl: "Haare", vi: "tóc", cat: "Cơ thể", note: ""),
        GWord(de: "Gesicht", art: "das", pl: "Gesichter", vi: "khuôn mặt", cat: "Cơ thể", note: ""),
        GWord(de: "Auge", art: "das", pl: "Augen", vi: "con mắt", cat: "Cơ thể", note: ""),
        GWord(de: "Ohr", art: "das", pl: "Ohren", vi: "cái tai", cat: "Cơ thể", note: ""),
        GWord(de: "Nase", art: "die", pl: "Nasen", vi: "cái mũi", cat: "Cơ thể", note: ""),
        GWord(de: "Mund", art: "der", pl: "Münder", vi: "cái miệng", cat: "Cơ thể", note: ""),
        GWord(de: "Lippe", art: "die", pl: "Lippen", vi: "môi", cat: "Cơ thể", note: ""),
        GWord(de: "Zahn", art: "der", pl: "Zähne", vi: "cái răng", cat: "Cơ thể", note: ""),
        GWord(de: "Zunge", art: "die", pl: "Zungen", vi: "cái lưỡi", cat: "Cơ thể", note: ""),
        GWord(de: "Hals", art: "der", pl: "Hälse", vi: "cổ, cổ họng", cat: "Cơ thể", note: ""),
        GWord(de: "Schulter", art: "die", pl: "Schultern", vi: "vai", cat: "Cơ thể", note: ""),
        GWord(de: "Arm", art: "der", pl: "Arme", vi: "cánh tay", cat: "Cơ thể", note: ""),
        GWord(de: "Ellbogen", art: "der", pl: "Ellbogen", vi: "khuỷu tay", cat: "Cơ thể", note: ""),
        GWord(de: "Hand", art: "die", pl: "Hände", vi: "bàn tay", cat: "Cơ thể", note: ""),
        GWord(de: "Finger", art: "der", pl: "Finger", vi: "ngón tay", cat: "Cơ thể", note: ""),
        GWord(de: "Daumen", art: "der", pl: "Daumen", vi: "ngón cái", cat: "Cơ thể", note: ""),
        GWord(de: "Nagel", art: "der", pl: "Nägel", vi: "móng tay; cái đinh", cat: "Cơ thể", note: ""),
        GWord(de: "Brust", art: "die", pl: "Brüste", vi: "ngực", cat: "Cơ thể", note: ""),
        GWord(de: "Bauch", art: "der", pl: "Bäuche", vi: "cái bụng", cat: "Cơ thể", note: ""),
        GWord(de: "Rücken", art: "der", pl: "Rücken", vi: "cái lưng", cat: "Cơ thể", note: ""),
        GWord(de: "Bein", art: "das", pl: "Beine", vi: "cái chân", cat: "Cơ thể", note: ""),
        GWord(de: "Knie", art: "das", pl: "Knie", vi: "đầu gối", cat: "Cơ thể", note: ""),
        GWord(de: "Fuß", art: "der", pl: "Füße", vi: "bàn chân", cat: "Cơ thể", note: ""),
        GWord(de: "Zeh", art: "der", pl: "Zehen", vi: "ngón chân", cat: "Cơ thể", note: ""),
        GWord(de: "Haut", art: "die", pl: "Häute", vi: "da", cat: "Cơ thể", note: ""),
        GWord(de: "Knochen", art: "der", pl: "Knochen", vi: "xương", cat: "Cơ thể", note: ""),
        GWord(de: "Muskel", art: "der", pl: "Muskeln", vi: "cơ bắp", cat: "Cơ thể", note: ""),
        GWord(de: "Herz", art: "das", pl: "Herzen", vi: "trái tim", cat: "Cơ thể", note: ""),
        GWord(de: "Lunge", art: "die", pl: "Lungen", vi: "phổi", cat: "Cơ thể", note: ""),
        GWord(de: "Magen", art: "der", pl: "Mägen", vi: "dạ dày", cat: "Cơ thể", note: ""),
        GWord(de: "Blut", art: "das", pl: nil, vi: "máu", cat: "Cơ thể", note: ""),

        // ── Quần áo ──
        GWord(de: "Hemd", art: "das", pl: "Hemden", vi: "áo sơ mi", cat: "Quần áo", note: ""),
        GWord(de: "Hose", art: "die", pl: "Hosen", vi: "cái quần", cat: "Quần áo", note: ""),
        GWord(de: "Rock", art: "der", pl: "Röcke", vi: "cái váy", cat: "Quần áo", note: ""),
        GWord(de: "Kleid", art: "das", pl: "Kleider", vi: "váy liền, đầm", cat: "Quần áo", note: ""),
        GWord(de: "Jacke", art: "die", pl: "Jacken", vi: "áo khoác", cat: "Quần áo", note: ""),
        GWord(de: "Mantel", art: "der", pl: "Mäntel", vi: "áo choàng", cat: "Quần áo", note: ""),
        GWord(de: "Pullover", art: "der", pl: "Pullover", vi: "áo len", cat: "Quần áo", note: ""),
        GWord(de: "T-Shirt", art: "das", pl: "T-Shirts", vi: "áo thun", cat: "Quần áo", note: ""),
        GWord(de: "Schuh", art: "der", pl: "Schuhe", vi: "giày", cat: "Quần áo", note: ""),
        GWord(de: "Socke", art: "die", pl: "Socken", vi: "tất, vớ", cat: "Quần áo", note: ""),
        GWord(de: "Stiefel", art: "der", pl: "Stiefel", vi: "giày bốt", cat: "Quần áo", note: ""),
        GWord(de: "Mütze", art: "die", pl: "Mützen", vi: "mũ len", cat: "Quần áo", note: ""),
        GWord(de: "Schal", art: "der", pl: "Schals", vi: "khăn quàng cổ", cat: "Quần áo", note: ""),
        GWord(de: "Handschuh", art: "der", pl: "Handschuhe", vi: "găng tay", cat: "Quần áo", note: ""),
        GWord(de: "Gürtel", art: "der", pl: "Gürtel", vi: "thắt lưng", cat: "Quần áo", note: ""),
        GWord(de: "Tasche", art: "die", pl: "Taschen", vi: "túi xách", cat: "Quần áo", note: ""),
        GWord(de: "Brille", art: "die", pl: "Brillen", vi: "kính đeo mắt", cat: "Quần áo", note: ""),
        GWord(de: "Ring", art: "der", pl: "Ringe", vi: "nhẫn", cat: "Quần áo", note: ""),
        GWord(de: "Knopf", art: "der", pl: "Knöpfe", vi: "cúc áo; nút bấm", cat: "Quần áo", note: ""),
        GWord(de: "Größe", art: "die", pl: "Größen", vi: "cỡ, kích thước", cat: "Quần áo", note: ""),

        // ── Nhà cửa (mở rộng) ──
        GWord(de: "Wohnzimmer", art: "das", pl: "Wohnzimmer", vi: "phòng khách", cat: "Nhà cửa", note: ""),
        GWord(de: "Schlafzimmer", art: "das", pl: "Schlafzimmer", vi: "phòng ngủ", cat: "Nhà cửa", note: ""),
        GWord(de: "Badezimmer", art: "das", pl: "Badezimmer", vi: "phòng tắm", cat: "Nhà cửa", note: ""),
        GWord(de: "Toilette", art: "die", pl: "Toiletten", vi: "nhà vệ sinh", cat: "Nhà cửa", note: ""),
        GWord(de: "Balkon", art: "der", pl: "Balkone", vi: "ban công", cat: "Nhà cửa", note: ""),
        GWord(de: "Garten", art: "der", pl: "Gärten", vi: "khu vườn", cat: "Nhà cửa", note: ""),
        GWord(de: "Treppe", art: "die", pl: "Treppen", vi: "cầu thang", cat: "Nhà cửa", note: ""),
        GWord(de: "Aufzug", art: "der", pl: "Aufzüge", vi: "thang máy", cat: "Nhà cửa", note: ""),
        GWord(de: "Wand", art: "die", pl: "Wände", vi: "bức tường", cat: "Nhà cửa", note: ""),
        GWord(de: "Boden", art: "der", pl: "Böden", vi: "sàn nhà", cat: "Nhà cửa", note: ""),
        GWord(de: "Decke", art: "die", pl: "Decken", vi: "trần nhà; cái chăn", cat: "Nhà cửa", note: "một từ, hai nghĩa"),
        GWord(de: "Lampe", art: "die", pl: "Lampen", vi: "cái đèn", cat: "Nhà cửa", note: ""),
        GWord(de: "Bett", art: "das", pl: "Betten", vi: "cái giường", cat: "Nhà cửa", note: ""),
        GWord(de: "Kissen", art: "das", pl: "Kissen", vi: "cái gối", cat: "Nhà cửa", note: ""),
        GWord(de: "Schrank", art: "der", pl: "Schränke", vi: "cái tủ", cat: "Nhà cửa", note: ""),
        GWord(de: "Regal", art: "das", pl: "Regale", vi: "cái kệ", cat: "Nhà cửa", note: ""),
        GWord(de: "Spiegel", art: "der", pl: "Spiegel", vi: "cái gương", cat: "Nhà cửa", note: ""),
        GWord(de: "Teppich", art: "der", pl: "Teppiche", vi: "tấm thảm", cat: "Nhà cửa", note: ""),
        GWord(de: "Vorhang", art: "der", pl: "Vorhänge", vi: "rèm cửa", cat: "Nhà cửa", note: ""),
        GWord(de: "Waschmaschine", art: "die", pl: "Waschmaschinen", vi: "máy giặt", cat: "Nhà cửa", note: ""),
        GWord(de: "Staubsauger", art: "der", pl: "Staubsauger", vi: "máy hút bụi", cat: "Nhà cửa", note: ""),
        GWord(de: "Bügeleisen", art: "das", pl: "Bügeleisen", vi: "bàn ủi", cat: "Nhà cửa", note: ""),
        GWord(de: "Seife", art: "die", pl: "Seifen", vi: "xà phòng", cat: "Nhà cửa", note: ""),
        GWord(de: "Handtuch", art: "das", pl: "Handtücher", vi: "khăn tắm", cat: "Nhà cửa", note: ""),
        GWord(de: "Zahnbürste", art: "die", pl: "Zahnbürsten", vi: "bàn chải đánh răng", cat: "Nhà cửa", note: ""),
        GWord(de: "Steckdose", art: "die", pl: "Steckdosen", vi: "ổ cắm điện", cat: "Nhà cửa", note: ""),
        GWord(de: "Nachbarin", art: "die", pl: "Nachbarinnen", vi: "bà hàng xóm", cat: "Nhà cửa", note: ""),

        // ── Đi lại (mở rộng) ──
        GWord(de: "U-Bahn", art: "die", pl: "U-Bahnen", vi: "tàu điện ngầm", cat: "Đi lại", note: ""),
        GWord(de: "Straßenbahn", art: "die", pl: "Straßenbahnen", vi: "tàu điện", cat: "Đi lại", note: ""),
        GWord(de: "Taxi", art: "das", pl: "Taxis", vi: "xe taxi", cat: "Đi lại", note: ""),
        GWord(de: "Flugzeug", art: "das", pl: "Flugzeuge", vi: "máy bay", cat: "Đi lại", note: ""),
        GWord(de: "Schiff", art: "das", pl: "Schiffe", vi: "con tàu, thuyền lớn", cat: "Đi lại", note: ""),
        GWord(de: "Fahrplan", art: "der", pl: "Fahrpläne", vi: "lịch chạy tàu xe", cat: "Đi lại", note: ""),
        GWord(de: "Verspätung", art: "die", pl: "Verspätungen", vi: "sự trễ giờ", cat: "Đi lại", note: ""),
        GWord(de: "Gleis", art: "das", pl: "Gleise", vi: "đường ray, ke ga", cat: "Đi lại", note: ""),
        GWord(de: "Richtung", art: "die", pl: "Richtungen", vi: "hướng đi", cat: "Đi lại", note: ""),
        GWord(de: "Kreuzung", art: "die", pl: "Kreuzungen", vi: "ngã tư", cat: "Đi lại", note: ""),
        GWord(de: "Brücke", art: "die", pl: "Brücken", vi: "cây cầu", cat: "Đi lại", note: ""),
        GWord(de: "Tankstelle", art: "die", pl: "Tankstellen", vi: "trạm xăng", cat: "Đi lại", note: ""),
        GWord(de: "Benzin", art: "das", pl: nil, vi: "xăng", cat: "Đi lại", note: ""),
        GWord(de: "Führerschein", art: "der", pl: "Führerscheine", vi: "bằng lái xe", cat: "Đi lại", note: ""),
        GWord(de: "Unfall", art: "der", pl: "Unfälle", vi: "tai nạn", cat: "Đi lại", note: ""),
        GWord(de: "Polizei", art: "die", pl: nil, vi: "cảnh sát", cat: "Đi lại", note: ""),
        GWord(de: "Parkplatz", art: "der", pl: "Parkplätze", vi: "chỗ đậu xe", cat: "Đi lại", note: ""),
        GWord(de: "Koffer", art: "der", pl: "Koffer", vi: "va li", cat: "Đi lại", note: ""),
        GWord(de: "Gepäck", art: "das", pl: nil, vi: "hành lý", cat: "Đi lại", note: ""),
        GWord(de: "Ampel", art: "die", pl: "Ampeln", vi: "đèn giao thông", cat: "Đi lại", note: ""),
        GWord(de: "Straße", art: "die", pl: "Straßen", vi: "con đường", cat: "Đi lại", note: ""),
        GWord(de: "Auto", art: "das", pl: "Autos", vi: "xe hơi", cat: "Đi lại", note: ""),
        GWord(de: "Fahrrad", art: "das", pl: "Fahrräder", vi: "xe đạp", cat: "Đi lại", note: ""),

        // ── Mua sắm (mở rộng) ──
        GWord(de: "Angebot", art: "das", pl: "Angebote", vi: "hàng khuyến mãi", cat: "Mua sắm", note: ""),
        GWord(de: "Rabatt", art: "der", pl: "Rabatte", vi: "giảm giá", cat: "Mua sắm", note: ""),
        GWord(de: "Quittung", art: "die", pl: "Quittungen", vi: "hóa đơn, biên lai", cat: "Mua sắm", note: ""),
        GWord(de: "Bargeld", art: "das", pl: nil, vi: "tiền mặt", cat: "Mua sắm", note: ""),
        GWord(de: "Kleingeld", art: "das", pl: nil, vi: "tiền lẻ", cat: "Mua sắm", note: ""),
        GWord(de: "Bäckerei", art: "die", pl: "Bäckereien", vi: "tiệm bánh mì", cat: "Mua sắm", note: ""),
        GWord(de: "Metzgerei", art: "die", pl: "Metzgereien", vi: "tiệm thịt", cat: "Mua sắm", note: ""),
        GWord(de: "Drogerie", art: "die", pl: "Drogerien", vi: "tiệm hóa mỹ phẩm", cat: "Mua sắm", note: ""),
        GWord(de: "Kiosk", art: "der", pl: "Kioske", vi: "quầy báo, ki-ốt", cat: "Mua sắm", note: ""),
        GWord(de: "Einkaufswagen", art: "der", pl: "Einkaufswagen", vi: "xe đẩy siêu thị", cat: "Mua sắm", note: ""),
        GWord(de: "Korb", art: "der", pl: "Körbe", vi: "cái giỏ", cat: "Mua sắm", note: ""),
        GWord(de: "Supermarkt", art: "der", pl: "Supermärkte", vi: "siêu thị", cat: "Mua sắm", note: ""),
        GWord(de: "Feiertag", art: "der", pl: "Feiertage", vi: "ngày lễ", cat: "Mua sắm", note: "cửa hàng đóng cửa!"),
        GWord(de: "Euro", art: "der", pl: "Euros", vi: "đồng euro", cat: "Mua sắm", note: ""),

        // ── Sức khỏe (mở rộng) ──
        GWord(de: "Husten", art: "der", pl: nil, vi: "ho", cat: "Sức khỏe", note: ""),
        GWord(de: "Schnupfen", art: "der", pl: nil, vi: "sổ mũi", cat: "Sức khỏe", note: ""),
        GWord(de: "Grippe", art: "die", pl: "Grippen", vi: "cúm", cat: "Sức khỏe", note: ""),
        GWord(de: "Wunde", art: "die", pl: "Wunden", vi: "vết thương", cat: "Sức khỏe", note: ""),
        GWord(de: "Pflaster", art: "das", pl: "Pflaster", vi: "băng dán cá nhân", cat: "Sức khỏe", note: ""),
        GWord(de: "Verband", art: "der", pl: "Verbände", vi: "băng gạc", cat: "Sức khỏe", note: ""),
        GWord(de: "Salbe", art: "die", pl: "Salben", vi: "thuốc mỡ", cat: "Sức khỏe", note: ""),
        GWord(de: "Impfung", art: "die", pl: "Impfungen", vi: "tiêm chủng", cat: "Sức khỏe", note: ""),
        GWord(de: "Blutdruck", art: "der", pl: nil, vi: "huyết áp", cat: "Sức khỏe", note: ""),
        GWord(de: "Krankmeldung", art: "die", pl: "Krankmeldungen", vi: "giấy báo ốm", cat: "Sức khỏe", note: ""),
        GWord(de: "Überweisung", art: "die", pl: "Überweisungen", vi: "giấy chuyển viện; chuyển khoản", cat: "Sức khỏe", note: "hai nghĩa"),
        GWord(de: "Wartezimmer", art: "das", pl: "Wartezimmer", vi: "phòng chờ", cat: "Sức khỏe", note: ""),
        GWord(de: "Sprechstunde", art: "die", pl: "Sprechstunden", vi: "giờ khám", cat: "Sức khỏe", note: ""),
        GWord(de: "Notaufnahme", art: "die", pl: "Notaufnahmen", vi: "phòng cấp cứu", cat: "Sức khỏe", note: ""),
        GWord(de: "Notruf", art: "der", pl: "Notrufe", vi: "cuộc gọi khẩn cấp", cat: "Sức khỏe", note: "112!"),
        GWord(de: "Krankenwagen", art: "der", pl: "Krankenwagen", vi: "xe cứu thương", cat: "Sức khỏe", note: ""),
        GWord(de: "Zahnarzt", art: "der", pl: "Zahnärzte", vi: "nha sĩ", cat: "Sức khỏe", note: ""),
        GWord(de: "Hausarzt", art: "der", pl: "Hausärzte", vi: "bác sĩ gia đình", cat: "Sức khỏe", note: ""),
        GWord(de: "Untersuchung", art: "die", pl: "Untersuchungen", vi: "cuộc khám bệnh", cat: "Sức khỏe", note: ""),
        GWord(de: "Allergie", art: "die", pl: "Allergien", vi: "dị ứng", cat: "Sức khỏe", note: ""),
        GWord(de: "Schwindel", art: "der", pl: nil, vi: "chóng mặt", cat: "Sức khỏe", note: ""),
        GWord(de: "Apotheker", art: "der", pl: "Apotheker", vi: "dược sĩ", cat: "Sức khỏe", note: ""),

        // ── Giấy tờ & cơ quan (mở rộng) ──
        GWord(de: "Anmeldung", art: "die", pl: "Anmeldungen", vi: "đăng ký (hộ khẩu)", cat: "Giấy tờ", note: ""),
        GWord(de: "Bescheid", art: "der", pl: "Bescheide", vi: "quyết định (giấy báo)", cat: "Giấy tờ", note: ""),
        GWord(de: "Bescheinigung", art: "die", pl: "Bescheinigungen", vi: "giấy chứng nhận", cat: "Giấy tờ", note: ""),
        GWord(de: "Geburtsurkunde", art: "die", pl: "Geburtsurkunden", vi: "giấy khai sinh", cat: "Giấy tờ", note: ""),
        GWord(de: "Aufenthaltstitel", art: "der", pl: "Aufenthaltstitel", vi: "giấy phép cư trú", cat: "Giấy tờ", note: ""),
        GWord(de: "Staatsangehörigkeit", art: "die", pl: "Staatsangehörigkeiten", vi: "quốc tịch", cat: "Giấy tờ", note: ""),
        GWord(de: "Rente", art: "die", pl: "Renten", vi: "lương hưu", cat: "Giấy tờ", note: ""),
        GWord(de: "Versicherung", art: "die", pl: "Versicherungen", vi: "bảo hiểm", cat: "Giấy tờ", note: ""),
        GWord(de: "Steuererklärung", art: "die", pl: "Steuererklärungen", vi: "khai thuế", cat: "Giấy tờ", note: ""),
        GWord(de: "Konto", art: "das", pl: "Konten", vi: "tài khoản", cat: "Giấy tờ", note: ""),
        GWord(de: "Kopie", art: "die", pl: "Kopien", vi: "bản sao", cat: "Giấy tờ", note: ""),
        GWord(de: "Passfoto", art: "das", pl: "Passfotos", vi: "ảnh thẻ", cat: "Giấy tờ", note: ""),
        GWord(de: "Behörde", art: "die", pl: "Behörden", vi: "cơ quan nhà nước", cat: "Giấy tờ", note: ""),
        GWord(de: "Botschaft", art: "die", pl: "Botschaften", vi: "đại sứ quán", cat: "Giấy tờ", note: ""),
        GWord(de: "Visum", art: "das", pl: "Visa", vi: "thị thực", cat: "Giấy tờ", note: ""),
        GWord(de: "Gebühr", art: "die", pl: "Gebühren", vi: "lệ phí", cat: "Giấy tờ", note: ""),

        // ── Công việc (mở rộng) ──
        GWord(de: "Bewerbung", art: "die", pl: "Bewerbungen", vi: "đơn xin việc", cat: "Công việc", note: ""),
        GWord(de: "Lebenslauf", art: "der", pl: "Lebensläufe", vi: "sơ yếu lý lịch", cat: "Công việc", note: ""),
        GWord(de: "Gehalt", art: "das", pl: "Gehälter", vi: "lương tháng", cat: "Công việc", note: ""),
        GWord(de: "Lohn", art: "der", pl: "Löhne", vi: "tiền công", cat: "Công việc", note: ""),
        GWord(de: "Schicht", art: "die", pl: "Schichten", vi: "ca làm việc", cat: "Công việc", note: ""),
        GWord(de: "Überstunde", art: "die", pl: "Überstunden", vi: "giờ làm thêm", cat: "Công việc", note: ""),
        GWord(de: "Kündigung", art: "die", pl: "Kündigungen", vi: "sự thôi việc, sa thải", cat: "Công việc", note: ""),
        GWord(de: "Ausbildung", art: "die", pl: "Ausbildungen", vi: "đào tạo nghề", cat: "Công việc", note: ""),
        GWord(de: "Praktikum", art: "das", pl: "Praktika", vi: "thực tập", cat: "Công việc", note: ""),
        GWord(de: "Kollegin", art: "die", pl: "Kolleginnen", vi: "nữ đồng nghiệp", cat: "Công việc", note: ""),
        GWord(de: "Besprechung", art: "die", pl: "Besprechungen", vi: "cuộc họp", cat: "Công việc", note: ""),
        GWord(de: "Firma", art: "die", pl: "Firmen", vi: "công ty", cat: "Công việc", note: ""),
        GWord(de: "Betrieb", art: "der", pl: "Betriebe", vi: "xí nghiệp", cat: "Công việc", note: ""),
        GWord(de: "Werkzeug", art: "das", pl: "Werkzeuge", vi: "dụng cụ", cat: "Công việc", note: ""),
        GWord(de: "Maschine", art: "die", pl: "Maschinen", vi: "máy móc", cat: "Công việc", note: ""),
        GWord(de: "Chef", art: "der", pl: "Chefs", vi: "sếp", cat: "Công việc", note: ""),

        // ── Thời gian (mở rộng) ──
        GWord(de: "Montag", art: "der", pl: "Montage", vi: "thứ Hai", cat: "Thời gian", note: ""),
        GWord(de: "Dienstag", art: "der", pl: "Dienstage", vi: "thứ Ba", cat: "Thời gian", note: ""),
        GWord(de: "Mittwoch", art: "der", pl: "Mittwoche", vi: "thứ Tư", cat: "Thời gian", note: ""),
        GWord(de: "Donnerstag", art: "der", pl: "Donnerstage", vi: "thứ Năm", cat: "Thời gian", note: ""),
        GWord(de: "Freitag", art: "der", pl: "Freitage", vi: "thứ Sáu", cat: "Thời gian", note: ""),
        GWord(de: "Samstag", art: "der", pl: "Samstage", vi: "thứ Bảy", cat: "Thời gian", note: ""),
        GWord(de: "Sonntag", art: "der", pl: "Sonntage", vi: "Chủ nhật", cat: "Thời gian", note: ""),
        GWord(de: "Januar", art: "der", pl: nil, vi: "tháng Một", cat: "Thời gian", note: ""),
        GWord(de: "Februar", art: "der", pl: nil, vi: "tháng Hai", cat: "Thời gian", note: ""),
        GWord(de: "März", art: "der", pl: nil, vi: "tháng Ba", cat: "Thời gian", note: ""),
        GWord(de: "April", art: "der", pl: nil, vi: "tháng Tư", cat: "Thời gian", note: ""),
        GWord(de: "Mai", art: "der", pl: nil, vi: "tháng Năm", cat: "Thời gian", note: ""),
        GWord(de: "Juni", art: "der", pl: nil, vi: "tháng Sáu", cat: "Thời gian", note: ""),
        GWord(de: "Juli", art: "der", pl: nil, vi: "tháng Bảy", cat: "Thời gian", note: ""),
        GWord(de: "August", art: "der", pl: nil, vi: "tháng Tám", cat: "Thời gian", note: ""),
        GWord(de: "September", art: "der", pl: nil, vi: "tháng Chín", cat: "Thời gian", note: ""),
        GWord(de: "Oktober", art: "der", pl: nil, vi: "tháng Mười", cat: "Thời gian", note: ""),
        GWord(de: "November", art: "der", pl: nil, vi: "tháng Mười Một", cat: "Thời gian", note: ""),
        GWord(de: "Dezember", art: "der", pl: nil, vi: "tháng Mười Hai", cat: "Thời gian", note: ""),
        GWord(de: "Frühling", art: "der", pl: "Frühlinge", vi: "mùa xuân", cat: "Thời gian", note: ""),
        GWord(de: "Sommer", art: "der", pl: "Sommer", vi: "mùa hè", cat: "Thời gian", note: ""),
        GWord(de: "Herbst", art: "der", pl: "Herbste", vi: "mùa thu", cat: "Thời gian", note: ""),
        GWord(de: "Winter", art: "der", pl: "Winter", vi: "mùa đông", cat: "Thời gian", note: ""),
        GWord(de: "Wochenende", art: "das", pl: "Wochenenden", vi: "cuối tuần", cat: "Thời gian", note: ""),
        GWord(de: "Kalender", art: "der", pl: "Kalender", vi: "lịch", cat: "Thời gian", note: ""),
        GWord(de: "Minute", art: "die", pl: "Minuten", vi: "phút", cat: "Thời gian", note: ""),
        GWord(de: "Sekunde", art: "die", pl: "Sekunden", vi: "giây", cat: "Thời gian", note: ""),
        GWord(de: "Stunde", art: "die", pl: "Stunden", vi: "tiếng đồng hồ", cat: "Thời gian", note: ""),

        // ── Thời tiết ──
        GWord(de: "Wetter", art: "das", pl: nil, vi: "thời tiết", cat: "Thời tiết", note: ""),
        GWord(de: "Sonne", art: "die", pl: "Sonnen", vi: "mặt trời", cat: "Thời tiết", note: ""),
        GWord(de: "Regen", art: "der", pl: nil, vi: "mưa", cat: "Thời tiết", note: ""),
        GWord(de: "Schnee", art: "der", pl: nil, vi: "tuyết", cat: "Thời tiết", note: ""),
        GWord(de: "Wind", art: "der", pl: "Winde", vi: "gió", cat: "Thời tiết", note: ""),
        GWord(de: "Wolke", art: "die", pl: "Wolken", vi: "mây", cat: "Thời tiết", note: ""),
        GWord(de: "Nebel", art: "der", pl: "Nebel", vi: "sương mù", cat: "Thời tiết", note: ""),
        GWord(de: "Gewitter", art: "das", pl: "Gewitter", vi: "dông bão", cat: "Thời tiết", note: ""),
        GWord(de: "Blitz", art: "der", pl: "Blitze", vi: "tia chớp", cat: "Thời tiết", note: ""),
        GWord(de: "Donner", art: "der", pl: nil, vi: "sấm", cat: "Thời tiết", note: ""),
        GWord(de: "Temperatur", art: "die", pl: "Temperaturen", vi: "nhiệt độ", cat: "Thời tiết", note: ""),
        GWord(de: "Grad", art: "das", pl: "Grade", vi: "độ (nhiệt độ)", cat: "Thời tiết", note: ""),
        GWord(de: "Himmel", art: "der", pl: "Himmel", vi: "bầu trời", cat: "Thời tiết", note: ""),
        GWord(de: "Sturm", art: "der", pl: "Stürme", vi: "cơn bão", cat: "Thời tiết", note: ""),
        GWord(de: "Hitze", art: "die", pl: nil, vi: "cái nóng", cat: "Thời tiết", note: ""),
        GWord(de: "Frost", art: "der", pl: "Fröste", vi: "băng giá", cat: "Thời tiết", note: ""),

        // ── Trường học ──
        GWord(de: "Lehrer", art: "der", pl: "Lehrer", vi: "thầy giáo", cat: "Trường học", note: ""),
        GWord(de: "Lehrerin", art: "die", pl: "Lehrerinnen", vi: "cô giáo", cat: "Trường học", note: ""),
        GWord(de: "Schüler", art: "der", pl: "Schüler", vi: "học sinh", cat: "Trường học", note: ""),
        GWord(de: "Klasse", art: "die", pl: "Klassen", vi: "lớp học", cat: "Trường học", note: ""),
        GWord(de: "Unterricht", art: "der", pl: nil, vi: "giờ học", cat: "Trường học", note: ""),
        GWord(de: "Hausaufgabe", art: "die", pl: "Hausaufgaben", vi: "bài tập về nhà", cat: "Trường học", note: ""),
        GWord(de: "Prüfung", art: "die", pl: "Prüfungen", vi: "kỳ thi", cat: "Trường học", note: ""),
        GWord(de: "Note", art: "die", pl: "Noten", vi: "điểm số", cat: "Trường học", note: ""),
        GWord(de: "Zeugnis", art: "das", pl: "Zeugnisse", vi: "học bạ, chứng chỉ", cat: "Trường học", note: ""),
        GWord(de: "Heft", art: "das", pl: "Hefte", vi: "quyển vở", cat: "Trường học", note: ""),
        GWord(de: "Stift", art: "der", pl: "Stifte", vi: "cây bút", cat: "Trường học", note: ""),
        GWord(de: "Tafel", art: "die", pl: "Tafeln", vi: "bảng đen", cat: "Trường học", note: ""),
        GWord(de: "Kindergarten", art: "der", pl: "Kindergärten", vi: "nhà trẻ", cat: "Trường học", note: ""),
        GWord(de: "Universität", art: "die", pl: "Universitäten", vi: "trường đại học", cat: "Trường học", note: ""),
        GWord(de: "Kurs", art: "der", pl: "Kurse", vi: "khóa học", cat: "Trường học", note: ""),
        GWord(de: "Schule", art: "die", pl: "Schulen", vi: "trường học", cat: "Trường học", note: ""),

        // ── Cảm xúc (danh từ) ──
        GWord(de: "Freude", art: "die", pl: "Freuden", vi: "niềm vui", cat: "Cảm xúc", note: ""),
        GWord(de: "Angst", art: "die", pl: "Ängste", vi: "nỗi sợ", cat: "Cảm xúc", note: ""),
        GWord(de: "Sorge", art: "die", pl: "Sorgen", vi: "nỗi lo", cat: "Cảm xúc", note: ""),
        GWord(de: "Glück", art: "das", pl: nil, vi: "hạnh phúc, may mắn", cat: "Cảm xúc", note: ""),
        GWord(de: "Liebe", art: "die", pl: nil, vi: "tình yêu", cat: "Cảm xúc", note: ""),
        GWord(de: "Wut", art: "die", pl: nil, vi: "cơn giận", cat: "Cảm xúc", note: ""),
        GWord(de: "Stress", art: "der", pl: nil, vi: "căng thẳng", cat: "Cảm xúc", note: ""),
        GWord(de: "Ruhe", art: "die", pl: nil, vi: "sự yên tĩnh", cat: "Cảm xúc", note: ""),
        GWord(de: "Heimat", art: "die", pl: nil, vi: "quê hương", cat: "Cảm xúc", note: ""),
        GWord(de: "Traum", art: "der", pl: "Träume", vi: "giấc mơ", cat: "Cảm xúc", note: "")
    ] + moreVerbs + moreAdjectives + moreSmallWords
}

extension GermanData {
    static let moreVerbs: [GWord] = [
        ("machen","làm"),("sagen","nói"),("sprechen","nói chuyện"),("fragen","hỏi"),
        ("antworten","trả lời"),("verstehen","hiểu"),("wiederholen","nhắc lại"),
        ("erklären","giải thích"),("bedeuten","có nghĩa là"),("heißen","tên là"),
        ("wohnen","cư ngụ"),("leben","sống"),("bleiben","ở lại"),("fahren","đi (xe)"),
        ("laufen","đi bộ, chạy"),("rennen","chạy nhanh"),("fliegen","bay"),
        ("reisen","du lịch"),("ankommen","đến nơi"),("abfahren","khởi hành"),
        ("einsteigen","lên xe"),("aussteigen","xuống xe"),("umsteigen","đổi xe"),
        ("holen","đi lấy"),("bringen","mang đến"),("tragen","mang, vác; mặc"),
        ("stellen","đặt (đứng)"),("legen","đặt (nằm)"),("sitzen","ngồi"),
        ("stehen","đứng"),("liegen","nằm"),("aufstehen","dậy"),("aufwachen","tỉnh giấc"),
        ("waschen","rửa, giặt"),("duschen","tắm vòi sen"),("putzen","lau chùi"),
        ("backen","nướng bánh"),("braten","chiên, rán"),("schneiden","cắt, thái"),
        ("probieren","thử, nếm thử"),("schmecken","có vị, ngon miệng"),
        ("bestellen","gọi món, đặt hàng"),("bezahlen","trả tiền"),("kosten","có giá"),
        ("sparen","tiết kiệm"),("verdienen","kiếm tiền"),("arbeiten","làm việc"),
        ("studieren","học đại học"),("rechnen","tính toán"),("zählen","đếm"),
        ("malen","vẽ"),("spielen","chơi"),("singen","hát"),("tanzen","nhảy múa"),
        ("lachen","cười"),("weinen","khóc"),("lächeln","mỉm cười"),
        ("denken","nghĩ"),("glauben","tin, cho rằng"),("wissen","biết (thông tin)"),
        ("kennen","quen biết"),("vergessen","quên"),("hoffen","hy vọng"),
        ("wünschen","chúc, mong"),("brauchen","cần"),("suchen","tìm"),
        ("finden","tìm thấy; thấy rằng"),("verlieren","đánh mất"),("geben","đưa, cho"),
        ("nehmen","lấy, cầm"),("schenken","tặng"),("verkaufen","bán"),
        ("öffnen","mở"),("schließen","đóng"),("anfangen","bắt đầu"),
        ("aufhören","ngừng lại"),("warten","chờ đợi"),("treffen","gặp gỡ"),
        ("besuchen","thăm"),("einladen","mời"),("anrufen","gọi điện"),
        ("telefonieren","nói chuyện điện thoại"),("schicken","gửi"),
        ("bekommen","nhận được"),("zeigen","chỉ, cho xem"),("danken","cảm ơn"),
        ("bitten","xin, nhờ"),("erlauben","cho phép"),("verbieten","cấm"),
        ("versuchen","cố gắng"),("schaffen","làm được"),("gewinnen","thắng"),
        ("feiern","ăn mừng"),("gratulieren","chúc mừng"),("wählen","chọn; bầu"),
        ("ändern","thay đổi"),("wechseln","đổi"),("reparieren","sửa chữa"),
        ("funktionieren","hoạt động"),("drücken","ấn, đẩy"),("ziehen","kéo"),
        ("heben","nâng lên"),("werfen","ném"),("fallen","ngã, rơi"),
        ("wandern","đi bộ đường dài"),("schwimmen","bơi"),("springen","nhảy"),
        ("fühlen","cảm thấy"),("husten","ho"),("atmen","thở"),("riechen","ngửi; có mùi"),
        ("anziehen","mặc vào"),("ausziehen","cởi ra; dọn đi"),
        ("anprobieren","mặc thử"),("passen","vừa vặn"),("gefallen","làm ưng ý"),
        ("gehören","thuộc về"),("fehlen","thiếu"),("stören","làm phiền"),
        ("klingeln","bấm chuông"),("klopfen","gõ cửa"),("packen","xếp đồ"),
        ("aufräumen","dọn dẹp"),("wegwerfen","vứt đi"),("mitnehmen","mang theo"),
        ("mitkommen","đi cùng"),("zuhören","lắng nghe"),("aufpassen","chú ý, trông chừng"),
        ("übersetzen","dịch"),("üben","luyện tập"),("unterschreiben","ký tên"),
        ("ausfüllen","điền (đơn)"),("abgeben","nộp"),("abholen","đón, đến lấy"),
        ("anmelden","đăng ký"),("kündigen","chấm dứt (hợp đồng)"),("mieten","thuê"),
        ("umziehen","chuyển nhà"),("sollen","nên (theo lời ai đó)"),("dürfen","được phép")
    ].map { GWord(de: $0.0, art: nil, pl: nil, vi: $0.1, cat: "Động từ", note: "") }

    static let moreAdjectives: [GWord] = [
        ("gut","tốt"),("schlecht","xấu, tệ"),("hässlich","xấu xí"),
        ("lang","dài"),("kurz","ngắn"),("breit","rộng"),("schmal","hẹp"),
        ("hoch","cao"),("tief","sâu"),("schwer","nặng; khó"),("leicht","nhẹ; dễ"),
        ("früh","sớm"),("spät","muộn"),("laut","ồn ào"),("leise","khe khẽ"),
        ("hell","sáng"),("dunkel","tối"),("warm","ấm"),("kühl","mát"),
        ("nass","ướt"),("trocken","khô"),("sauber","sạch"),("schmutzig","bẩn"),
        ("voll","đầy"),("leer","trống rỗng"),("offen","mở cửa"),
        ("geschlossen","đóng cửa"),("richtig","đúng"),("falsch","sai"),
        ("einfach","đơn giản"),("schwierig","khó khăn"),("wichtig","quan trọng"),
        ("egal","không quan trọng, sao cũng được"),("möglich","có thể"),
        ("gesund","khỏe mạnh"),("krank","ốm, bệnh"),("müde","mệt, buồn ngủ"),
        ("wach","tỉnh táo"),("hungrig","đói"),("satt","no"),("durstig","khát"),
        ("glücklich","hạnh phúc"),("traurig","buồn"),("fröhlich","vui vẻ"),
        ("wütend","tức giận"),("nervös","hồi hộp"),("ruhig","bình tĩnh, yên tĩnh"),
        ("freundlich","thân thiện"),("nett","dễ mến"),("höflich","lịch sự"),
        ("fleißig","chăm chỉ"),("faul","lười"),("klug","thông minh"),
        ("stark","khỏe, mạnh"),("schwach","yếu"),("reich","giàu"),("arm","nghèo"),
        ("teuer","đắt"),("billig","rẻ"),("günstig","giá tốt"),("kostenlos","miễn phí"),
        ("frisch","tươi"),("lecker","ngon"),("süß","ngọt; dễ thương"),
        ("sauer","chua"),("bitter","đắng"),("salzig","mặn"),("scharf","cay"),
        ("fertig","xong, sẵn sàng"),("kaputt","hỏng"),("ganz","toàn bộ; khá"),
        ("halb","một nửa"),("viel","nhiều"),("wenig","ít"),("mehr","nhiều hơn"),
        ("zusammen","cùng nhau"),("allein","một mình"),("gern","thích (làm gì)"),
        ("lieber","thích hơn"),("oft","thường xuyên"),("selten","hiếm khi"),
        ("immer","luôn luôn"),("nie","không bao giờ"),("manchmal","thỉnh thoảng"),
        ("wieder","lại, lần nữa"),("schon","đã, rồi"),("noch","còn, vẫn"),
        ("bald","sắp, chẳng bao lâu"),("sofort","ngay lập tức"),
        ("vielleicht","có lẽ"),("natürlich","dĩ nhiên"),("genau","chính xác"),
        ("ungefähr","khoảng chừng"),("fast","gần như"),("sehr","rất"),
        ("langsam","chậm"),("schnell","nhanh"),("neu","mới"),("alt","già; cũ"),
        ("jung","trẻ"),("groß","to, lớn"),("klein","nhỏ"),("schön","đẹp")
    ].map { GWord(de: $0.0, art: nil, pl: nil, vi: $0.1, cat: "Tính từ & trạng từ", note: "") }

    static let moreSmallWords: [GWord] = [
        ("ja","vâng, có"),("nein","không"),("doch","có chứ! (phản bác)"),
        ("bitte","xin mời; làm ơn"),("gerne","rất sẵn lòng"),
        ("wer","ai"),("was","cái gì"),("wann","khi nào"),("wo","ở đâu"),
        ("wohin","đi đâu"),("woher","từ đâu"),("warum","tại sao"),
        ("wie","như thế nào"),("wie viel","bao nhiêu"),("welcher","cái nào"),
        ("hier","ở đây"),("dort","ở kia"),("links","bên trái"),
        ("rechts","bên phải"),("geradeaus","thẳng phía trước"),
        ("oben","ở trên"),("unten","ở dưới"),("vorne","phía trước"),
        ("hinten","phía sau"),("zwischen","ở giữa"),("neben","bên cạnh")
    ].map { GWord(de: $0.0, art: nil, pl: nil, vi: $0.1, cat: "Giao tiếp", note: "") }

    static let morePhrases: [GPhrase] = [
        // Ở nhà hàng
        GPhrase(de: "Einen Tisch für zwei, bitte.", vi: "Cho một bàn hai người.", cat: "Ở nhà hàng"),
        GPhrase(de: "Die Speisekarte, bitte.", vi: "Cho xem thực đơn.", cat: "Ở nhà hàng"),
        GPhrase(de: "Was können Sie empfehlen?", vi: "Ông/bà gợi ý món gì?", cat: "Ở nhà hàng"),
        GPhrase(de: "Ich hätte gern die Suppe.", vi: "Tôi muốn món súp.", cat: "Ở nhà hàng"),
        GPhrase(de: "Ohne Zwiebeln, bitte.", vi: "Xin đừng cho hành.", cat: "Ở nhà hàng"),
        GPhrase(de: "Das schmeckt sehr gut.", vi: "Món này rất ngon.", cat: "Ở nhà hàng"),
        GPhrase(de: "Die Rechnung, bitte.", vi: "Cho xin hóa đơn.", cat: "Ở nhà hàng"),
        GPhrase(de: "Getrennt oder zusammen?", vi: "Trả riêng hay trả chung?", cat: "Ở nhà hàng"),
        GPhrase(de: "Stimmt so.", vi: "Không cần thối lại.", cat: "Ở nhà hàng"),
        GPhrase(de: "Ist dieser Platz frei?", vi: "Chỗ này còn trống không?", cat: "Ở nhà hàng"),
        GPhrase(de: "Zum Mitnehmen, bitte.", vi: "Cho mang về.", cat: "Ở nhà hàng"),
        GPhrase(de: "Ein Glas Wasser, bitte.", vi: "Cho một ly nước.", cat: "Ở nhà hàng"),
        GPhrase(de: "Guten Appetit!", vi: "Chúc ngon miệng!", cat: "Ở nhà hàng"),
        GPhrase(de: "Es war sehr lecker, danke.", vi: "Rất ngon, cảm ơn.", cat: "Ở nhà hàng"),
        // Hỏi đường
        GPhrase(de: "Entschuldigung, wo ist der Bahnhof?", vi: "Xin lỗi, nhà ga ở đâu?", cat: "Hỏi đường"),
        GPhrase(de: "Wie komme ich zur Apotheke?", vi: "Đi đến hiệu thuốc thế nào?", cat: "Hỏi đường"),
        GPhrase(de: "Ist es weit von hier?", vi: "Có xa đây không?", cat: "Hỏi đường"),
        GPhrase(de: "Gehen Sie geradeaus.", vi: "Ông/bà đi thẳng.", cat: "Hỏi đường"),
        GPhrase(de: "An der Ampel links.", vi: "Đến đèn giao thông rẽ trái.", cat: "Hỏi đường"),
        GPhrase(de: "Die zweite Straße rechts.", vi: "Đường thứ hai bên phải.", cat: "Hỏi đường"),
        GPhrase(de: "Es ist gleich um die Ecke.", vi: "Ngay góc phố thôi.", cat: "Hỏi đường"),
        GPhrase(de: "Ich habe mich verlaufen.", vi: "Tôi bị lạc đường.", cat: "Hỏi đường"),
        GPhrase(de: "Welcher Bus fährt ins Zentrum?", vi: "Xe buýt nào vào trung tâm?", cat: "Hỏi đường"),
        GPhrase(de: "Wo muss ich umsteigen?", vi: "Tôi phải đổi xe ở đâu?", cat: "Hỏi đường"),
        GPhrase(de: "Wann fährt der nächste Zug?", vi: "Chuyến tàu tới mấy giờ chạy?", cat: "Hỏi đường"),
        GPhrase(de: "Von welchem Gleis fährt der Zug?", vi: "Tàu chạy từ đường ray số mấy?", cat: "Hỏi đường"),
        // Gọi điện
        GPhrase(de: "Hallo, hier ist Frau Vu.", vi: "A lô, tôi là bà Vũ.", cat: "Gọi điện"),
        GPhrase(de: "Kann ich bitte mit Herrn Müller sprechen?", vi: "Cho tôi nói chuyện với ông Müller?", cat: "Gọi điện"),
        GPhrase(de: "Einen Moment, bitte.", vi: "Xin chờ một chút.", cat: "Gọi điện"),
        GPhrase(de: "Er ist gerade nicht da.", vi: "Ông ấy hiện không có ở đây.", cat: "Gọi điện"),
        GPhrase(de: "Kann ich eine Nachricht hinterlassen?", vi: "Tôi nhắn lại được không?", cat: "Gọi điện"),
        GPhrase(de: "Ich möchte einen Termin vereinbaren.", vi: "Tôi muốn đặt lịch hẹn.", cat: "Gọi điện"),
        GPhrase(de: "Ich muss den Termin leider absagen.", vi: "Rất tiếc tôi phải hủy hẹn.", cat: "Gọi điện"),
        GPhrase(de: "Können wir den Termin verschieben?", vi: "Mình dời lịch hẹn được không?", cat: "Gọi điện"),
        GPhrase(de: "Ich verstehe Sie schlecht.", vi: "Tôi nghe không rõ.", cat: "Gọi điện"),
        GPhrase(de: "Können Sie das per E-Mail schicken?", vi: "Gửi qua email được không?", cat: "Gọi điện"),
        GPhrase(de: "Auf Wiederhören!", vi: "Chào tạm biệt (qua điện thoại)!", cat: "Gọi điện"),
        // Thời tiết & chuyện phiếm
        GPhrase(de: "Schönes Wetter heute, oder?", vi: "Hôm nay trời đẹp nhỉ?", cat: "Thời tiết & chuyện phiếm"),
        GPhrase(de: "Es ist sehr kalt draußen.", vi: "Ngoài trời rất lạnh.", cat: "Thời tiết & chuyện phiếm"),
        GPhrase(de: "Morgen soll es regnen.", vi: "Nghe nói mai trời mưa.", cat: "Thời tiết & chuyện phiếm"),
        GPhrase(de: "Ziehen Sie sich warm an!", vi: "Nhớ mặc ấm nhé!", cat: "Thời tiết & chuyện phiếm"),
        GPhrase(de: "Wie war Ihr Wochenende?", vi: "Cuối tuần của ông/bà thế nào?", cat: "Thời tiết & chuyện phiếm"),
        GPhrase(de: "Was machen Sie am Wochenende?", vi: "Cuối tuần ông/bà làm gì?", cat: "Thời tiết & chuyện phiếm"),
        GPhrase(de: "Bis später!", vi: "Hẹn lát nữa!", cat: "Thời tiết & chuyện phiếm"),
        GPhrase(de: "Schönen Feierabend!", vi: "Chúc buổi tối nghỉ ngơi vui vẻ!", cat: "Thời tiết & chuyện phiếm"),
        GPhrase(de: "Gute Besserung!", vi: "Chúc mau khỏe!", cat: "Thời tiết & chuyện phiếm"),
        GPhrase(de: "Viel Glück!", vi: "Chúc may mắn!", cat: "Thời tiết & chuyện phiếm"),
        GPhrase(de: "Herzlichen Glückwunsch zum Geburtstag!", vi: "Chúc mừng sinh nhật!", cat: "Thời tiết & chuyện phiếm"),
        GPhrase(de: "Frohes neues Jahr!", vi: "Chúc mừng năm mới!", cat: "Thời tiết & chuyện phiếm"),
        GPhrase(de: "Schöne Feiertage!", vi: "Chúc kỳ nghỉ lễ vui vẻ!", cat: "Thời tiết & chuyện phiếm"),
        GPhrase(de: "Grüßen Sie Ihre Familie!", vi: "Cho tôi gửi lời hỏi thăm gia đình!", cat: "Thời tiết & chuyện phiếm"),
        // Gia đình & cảm xúc
        GPhrase(de: "Ich habe zwei Kinder.", vi: "Tôi có hai người con.", cat: "Gia đình & cảm xúc"),
        GPhrase(de: "Meine Tochter wohnt in Berlin.", vi: "Con gái tôi sống ở Berlin.", cat: "Gia đình & cảm xúc"),
        GPhrase(de: "Wir sind seit dreißig Jahren verheiratet.", vi: "Chúng tôi cưới nhau ba mươi năm rồi.", cat: "Gia đình & cảm xúc"),
        GPhrase(de: "Ich vermisse meine Heimat.", vi: "Tôi nhớ quê hương.", cat: "Gia đình & cảm xúc"),
        GPhrase(de: "Ich freue mich sehr.", vi: "Tôi rất vui.", cat: "Gia đình & cảm xúc"),
        GPhrase(de: "Machen Sie sich keine Sorgen.", vi: "Ông/bà đừng lo lắng.", cat: "Gia đình & cảm xúc"),
        GPhrase(de: "Alles wird gut.", vi: "Mọi chuyện sẽ ổn thôi.", cat: "Gia đình & cảm xúc"),
        GPhrase(de: "Ich bin stolz auf dich.", vi: "Bố mẹ tự hào về con.", cat: "Gia đình & cảm xúc"),
        GPhrase(de: "Das Essen ist fertig!", vi: "Cơm xong rồi!", cat: "Gia đình & cảm xúc"),
        GPhrase(de: "Komm gut nach Hause.", vi: "Về nhà cẩn thận nhé.", cat: "Gia đình & cảm xúc"),
        GPhrase(de: "Schlaf gut!", vi: "Ngủ ngon nhé!", cat: "Gia đình & cảm xúc"),
        GPhrase(de: "Ich hab dich lieb.", vi: "Bố/mẹ thương con.", cat: "Gia đình & cảm xúc"),
        // Mua sắm & phòng khám (bổ sung)
        GPhrase(de: "Ich möchte das umtauschen.", vi: "Tôi muốn đổi cái này.", cat: "Mua sắm"),
        GPhrase(de: "Haben Sie das eine Nummer größer?", vi: "Có cỡ lớn hơn không?", cat: "Mua sắm"),
        GPhrase(de: "Wo finde ich Reis?", vi: "Gạo ở chỗ nào?", cat: "Mua sắm"),
        GPhrase(de: "Das ist alles, danke.", vi: "Vậy là đủ rồi, cảm ơn.", cat: "Mua sắm"),
        GPhrase(de: "Ich habe seit drei Tagen Husten.", vi: "Tôi ho ba ngày nay rồi.", cat: "Ở phòng khám"),
        GPhrase(de: "Mir ist schwindelig.", vi: "Tôi thấy chóng mặt.", cat: "Ở phòng khám"),
        GPhrase(de: "Ich bin allergisch gegen Pollen.", vi: "Tôi dị ứng phấn hoa.", cat: "Ở phòng khám"),
        GPhrase(de: "Brauche ich ein Rezept?", vi: "Tôi có cần đơn thuốc không?", cat: "Ở phòng khám")
    ]
}
