import Foundation

// Erweiterungswortschatz Con-Profil (v1.7)
extension VietnameseData {

    static let words: [VWord] = dedupe(coreWords + moreWords)
    static let sentences: [VSentence] = coreSentences + moreSentences

    private static func dedupe(_ list: [VWord]) -> [VWord] {
        var seen = Set<String>()
        return list.filter { seen.insert($0.v.lowercased()).inserted }
    }

    static let moreWords: [VWord] = [
        // Körper
        ("đầu","Kopf","Körper",""),("mắt","Auge","Körper",""),("mũi","Nase","Körper",""),
        ("miệng","Mund","Körper",""),("tai","Ohr","Körper",""),("tóc","Haar","Körper",""),
        ("răng","Zahn","Körper",""),("lưỡi","Zunge","Körper",""),("cổ","Hals","Körper",""),
        ("vai","Schulter","Körper",""),("tay","Arm, Hand","Körper",""),
        ("chân","Bein, Fuß","Körper",""),("bụng","Bauch","Körper",""),
        ("lưng","Rücken","Körper",""),("tim","Herz","Körper",""),
        ("máu","Blut","Körper",""),("da","Haut","Körper",""),
        ("xương","Knochen","Körper",""),("ngón tay","Finger","Körper",""),
        // Natur & Wetter
        ("mưa","Regen","Natur",""),("nắng","Sonnenschein","Natur",""),
        ("gió","Wind","Natur",""),("mây","Wolke","Natur",""),
        ("tuyết","Schnee","Natur",""),("bão","Sturm","Natur",""),
        ("trời","Himmel, Wetter","Natur",""),("biển","Meer","Natur",""),
        ("núi","Berg","Natur",""),("sông","Fluss","Natur",""),
        ("hồ","See","Natur",""),("cây","Baum","Natur",""),
        ("hoa","Blume","Natur",""),("lá","Blatt","Natur",""),
        ("chó","Hund","Natur",""),("mèo","Katze","Natur",""),
        ("chim","Vogel","Natur",""),("mặt trời","Sonne","Natur",""),
        ("mặt trăng","Mond","Natur",""),("sao","Stern","Natur",""),
        // Stadt & Orte
        ("thành phố","Stadt","Stadt",""),("làng","Dorf","Stadt",""),
        ("phố","Straße, Gasse","Stadt",""),("công viên","Park","Stadt",""),
        ("bệnh viện","Krankenhaus","Stadt",""),("trường học","Schule","Stadt",""),
        ("chùa","Pagode","Stadt",""),("nhà thờ","Kirche","Stadt",""),
        ("khách sạn","Hotel","Stadt",""),("sân bay","Flughafen","Stadt",""),
        ("bến xe","Busbahnhof","Stadt",""),("nhà ga","Bahnhof","Stadt",""),
        ("bưu điện","Post","Stadt",""),("ngân hàng","Bank","Stadt",""),
        ("siêu thị","Supermarkt","Stadt",""),("hiệu thuốc","Apotheke","Stadt","miền Nam: nhà thuốc"),
        ("cầu","Brücke","Stadt",""),("vé","Ticket, Fahrkarte","Stadt",""),
        ("xe máy","Motorrad, Moped","Stadt",""),("ô tô","Auto","Stadt","miền Nam: xe hơi"),
        ("tàu","Zug; Schiff","Stadt",""),("thuyền","Boot","Stadt",""),
        // Mehr Verben
        ("giận","wütend sein","Tun",""),("sợ","Angst haben","Tun",""),
        ("ghét","hassen, nicht mögen","Tun",""),("cười","lachen","Tun",""),
        ("khóc","weinen","Tun",""),("hát","singen","Tun",""),
        ("nhảy","tanzen, springen","Tun",""),("chạy","rennen","Tun",""),
        ("bơi","schwimmen","Tun",""),("bay","fliegen","Tun",""),
        ("ngồi","sitzen","Tun",""),("đứng","stehen","Tun",""),
        ("nằm","liegen","Tun",""),("mở","öffnen","Tun",""),
        ("đóng","schließen","Tun",""),("tìm","suchen","Tun",""),
        ("thấy","sehen, finden","Tun",""),("gặp","treffen","Tun",""),
        ("trả lời","antworten","Tun",""),("trả tiền","bezahlen","Tun",""),
        ("làm việc","arbeiten","Tun",""),("nghỉ","sich ausruhen","Tun",""),
        ("chơi","spielen","Tun",""),("tập","üben, trainieren","Tun",""),
        ("nấu ăn","kochen","Tun",""),("rửa","waschen, spülen","Tun",""),
        ("lau","wischen","Tun",""),("quét","fegen","Tun",""),
        ("giặt","Wäsche waschen","Tun",""),("cắt","schneiden","Tun",""),
        ("phải","müssen","Tun",""),("nên","sollten","Tun",""),
        ("có thể","können","Tun",""),("bắt đầu","anfangen","Tun",""),
        ("kết thúc","enden","Tun",""),("sống","leben","Tun",""),
        ("chết","sterben","Tun",""),("cho phép","erlauben","Tun",""),
        ("gửi","schicken","Tun",""),("nhận","bekommen","Tun",""),
        ("chọn","wählen","Tun",""),("đổi","wechseln, tauschen","Tun",""),
        ("sửa","reparieren","Tun",""),("xây","bauen","Tun",""),
        ("mang","tragen, bringen","Tun",""),("đưa","geben, reichen","Tun",""),
        ("kể","erzählen","Tun",""),("hứa","versprechen","Tun",""),
        // Mehr Eigenschaften
        ("sạch","sauber","Eigenschaft",""),("bẩn","schmutzig","Eigenschaft","miền Nam: dơ"),
        ("đầy","voll","Eigenschaft",""),("trống","leer","Eigenschaft",""),
        ("rộng","breit, geräumig","Eigenschaft",""),("hẹp","eng","Eigenschaft",""),
        ("cao","hoch, groß (Person)","Eigenschaft",""),("thấp","niedrig, klein (Person)","Eigenschaft",""),
        ("dài","lang","Eigenschaft",""),("ngắn","kurz","Eigenschaft",""),
        ("nặng","schwer","Eigenschaft",""),("nhẹ","leicht","Eigenschaft",""),
        ("đắt","teuer","Eigenschaft","miền Nam: mắc"),("rẻ","billig","Eigenschaft",""),
        ("ngọt","süß","Eigenschaft",""),("chua","sauer","Eigenschaft",""),
        ("cay","scharf","Eigenschaft",""),("mặn","salzig","Eigenschaft",""),
        ("nhạt","fad, mild","Eigenschaft",""),("thơm","duftend","Eigenschaft",""),
        ("sớm","früh","Eigenschaft",""),("muộn","spät","Eigenschaft","miền Nam: trễ"),
        ("đúng","richtig","Eigenschaft",""),("sai","falsch","Eigenschaft",""),
        ("quan trọng","wichtig","Eigenschaft",""),("bận","beschäftigt","Eigenschaft",""),
        ("rảnh","frei (Zeit haben)","Eigenschaft",""),("giàu","reich","Eigenschaft",""),
        ("nghèo","arm","Eigenschaft",""),("mạnh","stark","Eigenschaft",""),
        ("yếu","schwach","Eigenschaft",""),("ồn","laut","Eigenschaft",""),
        ("yên tĩnh","ruhig, still","Eigenschaft",""),
        // Alltag & Dinge
        ("quà","Geschenk","Alltag",""),("sinh nhật","Geburtstag","Alltag",""),
        ("đám cưới","Hochzeit","Alltag",""),("lễ","Fest, Feiertag","Alltag",""),
        ("Tết","vietnamesisches Neujahr","Alltag",""),("khách","Gast","Alltag",""),
        ("bạn bè","Freunde","Alltag",""),("hàng xóm","Nachbarn","Alltag",""),
        ("ông bà","Großeltern","Alltag",""),("con gái","Tochter, Mädchen","Alltag",""),
        ("con trai","Sohn, Junge","Alltag",""),("tình yêu","Liebe","Alltag",""),
        ("sức khỏe","Gesundheit","Alltag",""),("niềm vui","Freude","Alltag",""),
        ("giấc mơ","Traum","Alltag",""),("câu chuyện","Geschichte, Erzählung","Alltag",""),
        ("tin tức","Nachrichten","Alltag",""),("báo","Zeitung","Alltag",""),
        ("ti vi","Fernseher","Alltag",""),("máy tính","Computer","Alltag",""),
        ("mạng","Internet, Netz","Alltag",""),("ảnh","Foto","Alltag",""),
        ("phim","Film","Alltag",""),("nhạc","Musik","Alltag",""),
        ("bài hát","Lied","Alltag",""),("trò chơi","Spiel","Alltag",""),
        ("bóng đá","Fußball","Alltag",""),("thể thao","Sport","Alltag",""),
        ("du lịch","Reisen","Alltag",""),("kỳ nghỉ","Urlaub","Alltag",""),
        ("chìa khóa","Schlüssel","Alltag",""),("ví","Geldbörse","Alltag",""),
        ("kính","Brille","Alltag",""),("đồng hồ","Uhr","Alltag",""),
        ("bản đồ","Landkarte","Alltag",""),("thư","Brief","Alltag",""),
        ("lương","Gehalt","Alltag",""),("thuế","Steuer","Alltag",""),
        ("hộ chiếu","Reisepass","Alltag",""),("thị thực","Visum","Alltag",""),
        ("bảo hiểm","Versicherung","Alltag",""),("giấy tờ","Papiere, Dokumente","Alltag","")
    ].map { VWord(v: $0.0, de: $0.1, cat: $0.2, note: $0.3) }

    static let moreSentences: [VSentence] = [
        VSentence(vi: "Hôm nay trời đẹp quá.", de: "Heute ist das Wetter richtig schön."),
        VSentence(vi: "Cuối tuần này con rảnh không?", de: "Hast du dieses Wochenende Zeit?"),
        VSentence(vi: "Mình đi uống cà phê nhé.", de: "Lass uns einen Kaffee trinken gehen."),
        VSentence(vi: "Anh ăn sáng chưa?", de: "Hast du schon gefrühstückt?"),
        VSentence(vi: "Chị đang làm gì đấy?", de: "Was machst du gerade?"),
        VSentence(vi: "Con nhớ nhà lắm.", de: "Ich habe großes Heimweh."),
        VSentence(vi: "Bao giờ con về thăm ông bà?", de: "Wann besuchst du Oma und Opa?"),
        VSentence(vi: "Đường này kẹt xe quá.", de: "Auf dieser Straße ist so viel Stau."),
        VSentence(vi: "Cho tôi hỏi một chút.", de: "Darf ich kurz etwas fragen?"),
        VSentence(vi: "Cái này bao nhiêu tiền?", de: "Wie viel kostet das?"),
        VSentence(vi: "Đắt quá, bớt chút được không?", de: "Zu teuer — geht da noch was am Preis?"),
        VSentence(vi: "Tôi muốn đặt bàn cho hai người.", de: "Ich möchte einen Tisch für zwei reservieren."),
        VSentence(vi: "Món này ngon tuyệt.", de: "Dieses Gericht ist ausgezeichnet."),
        VSentence(vi: "Cho tôi xin hóa đơn.", de: "Die Rechnung, bitte."),
        VSentence(vi: "Chúc mừng sinh nhật!", de: "Herzlichen Glückwunsch zum Geburtstag!"),
        VSentence(vi: "Chúc mừng năm mới!", de: "Frohes neues Jahr!"),
        VSentence(vi: "Tết này cả nhà về quê.", de: "Dieses Tết fährt die ganze Familie in die Heimat."),
        VSentence(vi: "Bà ơi, bà kể chuyện ngày xưa đi.", de: "Oma, erzähl von früher!"),
        VSentence(vi: "Con gái tôi mới đi làm.", de: "Meine Tochter hat gerade angefangen zu arbeiten."),
        VSentence(vi: "Dạo này công việc thế nào?", de: "Wie läuft die Arbeit zurzeit?"),
        VSentence(vi: "Tôi hơi mệt, muốn nghỉ sớm.", de: "Ich bin etwas müde und will früh schlafen gehen."),
        VSentence(vi: "Ngủ ngon nhé, mai gặp lại.", de: "Schlaf gut, bis morgen."),
        VSentence(vi: "Đừng lo, mọi chuyện sẽ ổn thôi.", de: "Keine Sorge, alles wird gut."),
        VSentence(vi: "Cảm ơn con đã giúp mẹ.", de: "Danke, dass du Mama geholfen hast."),
        VSentence(vi: "Trời mưa rồi, mang ô theo nhé.", de: "Es regnet — nimm einen Schirm mit."),
        VSentence(vi: "Em thích nghe nhạc Việt Nam.", de: "Ich höre gern vietnamesische Musik."),
        VSentence(vi: "Cuốn sách này hay lắm.", de: "Dieses Buch ist richtig gut."),
        VSentence(vi: "Mình chụp một tấm ảnh nhé.", de: "Lass uns ein Foto machen."),
        VSentence(vi: "Lâu quá không gặp!", de: "Lange nicht gesehen!"),
        VSentence(vi: "Hẹn gặp lại tuần sau.", de: "Bis nächste Woche!")
    ]
}
